import { Inter } from "next/font/google";
import "./globals.css";
import SideBarComponent from "@/components/SideBarComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body class="bg-[#717171] min-h-screen" className={inter.className}>
        <div className="w-full min-h-screen">
          <div className="flex lg:flex-row flex-col gap-2 w-full min-h-screen pt-6 ">
            <div className="w-[35%] h-screen fixed top-0 left-0 mt-6">
              <SideBarComponent />
            </div>
            <div className="w-[65%] rounded-md ml-[35%]">{children}</div>
          </div>

          <div className="bg-[#0C0C0C] text-white p-3 w-full">
            &copy;2024 All rights Reserved developed by Jemi States
          </div>
        </div>
      </body>
    </html>
  );
}
